"""
Segmentation templates for different pet types
Defines spatial regions for body part segmentation
"""

TEMPLATES = {
    "quadruped": {
        "head": {
            "y_min": 0.7,
            "y_max": 1.0,
            "x_min": 0.0,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "body": {
            "y_min": 0.3,
            "y_max": 0.7,
            "x_min": 0.0,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "leg_front_l": {
            "y_min": 0.0,
            "y_max": 0.5,
            "x_min": 0.0,
            "x_max": 0.5,
            "z_min": 0.5,
            "z_max": 1.0,
        },
        "leg_front_r": {
            "y_min": 0.0,
            "y_max": 0.5,
            "x_min": 0.5,
            "x_max": 1.0,
            "z_min": 0.5,
            "z_max": 1.0,
        },
        "leg_back_l": {
            "y_min": 0.0,
            "y_max": 0.5,
            "x_min": 0.0,
            "x_max": 0.5,
            "z_min": 0.0,
            "z_max": 0.5,
        },
        "leg_back_r": {
            "y_min": 0.0,
            "y_max": 0.5,
            "x_min": 0.5,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 0.5,
        },
        "tail": {
            "y_min": 0.2,
            "y_max": 0.7,
            "x_min": 0.0,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 0.3,
        },
    },
    "biped": {
        "head": {
            "y_min": 0.8,
            "y_max": 1.0,
            "x_min": 0.0,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "body": {
            "y_min": 0.4,
            "y_max": 0.8,
            "x_min": 0.0,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "leg_l": {
            "y_min": 0.0,
            "y_max": 0.4,
            "x_min": 0.0,
            "x_max": 0.5,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "leg_r": {
            "y_min": 0.0,
            "y_max": 0.4,
            "x_min": 0.5,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "arm_l": {
            "y_min": 0.5,
            "y_max": 0.9,
            "x_min": 0.0,
            "x_max": 0.4,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "arm_r": {
            "y_min": 0.5,
            "y_max": 0.9,
            "x_min": 0.6,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 1.0,
        },
    },
    "flying": {
        "head": {
            "y_min": 0.7,
            "y_max": 1.0,
            "x_min": 0.0,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "body": {
            "y_min": 0.3,
            "y_max": 0.7,
            "x_min": 0.0,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "wing_l": {
            "y_min": 0.3,
            "y_max": 0.8,
            "x_min": 0.0,
            "x_max": 0.4,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "wing_r": {
            "y_min": 0.3,
            "y_max": 0.8,
            "x_min": 0.6,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "leg_l": {
            "y_min": 0.0,
            "y_max": 0.5,
            "x_min": 0.0,
            "x_max": 0.5,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "leg_r": {
            "y_min": 0.0,
            "y_max": 0.5,
            "x_min": 0.5,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 1.0,
        },
        "tail": {
            "y_min": 0.2,
            "y_max": 0.7,
            "x_min": 0.0,
            "x_max": 1.0,
            "z_min": 0.0,
            "z_max": 0.3,
        },
    },
}
